server:
  port: 9000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/index?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  redis:
    database: 1
    port: 6379
    host: 127.0.0.1


logging:
  level:
    root: info
    com:
      sec:
        kill:
          repo: debug

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.sec.kill.model
  configuration:
    map-underscore-to-camel-case: true
